### ISSUE TITLE
Translate the Chinese Edition README.md to English Edition

### ISSUE THREAD

**Issue by zmzhouXJTU** [ACLoong/Problem-sets#10]
The Chinese edition of README.md have been posted on the Github. Now you should translate it to an English editoin.

From this work , you can master some skills as follows :
1. Improve your English writing skills
2. Learn the basic grammar of Markdown
3. Be familiar with the general process of your future job.

Come on ! Have a try @July-zhang

**Comment by July-zhang** [comment]
let me try.

**Comment by wangqing1218** [comment]
Why close this issue?
