### ISSUE TITLE
Translate Introductions.md to an English one.

### ISSUE THREAD

**Issue by wangqing1218** [ACLoong/Problem-sets#16]
Let @zmzhouXJTU give the details of this issue.

**Comment by zmzhouXJTU** [comment]
Just as the README file , it has both Chinese and English edition . So in this issue, what you need to do is 

that **translate the Chinese Introductions.md edition to an English edition** . 

Not only can this issue improve your English writing skills but also you can be familar with the basic 

grammar of Markdown through finishing the issue.

So, Come on, Have a try!!! @wangqing1218 @throcean
