### ISSUE TITLE
Rewrite README.md file.

### ISSUE THREAD

**Issue by wangqing1218** [ACLoong/Problem-sets#6]
For every follower to have a clear understanding about this repository, it's necessary to write a great **README.md** document.

So,the 1st thing we have to do is that rewriting the **README.md** file by markdown.
It may look like this:
```markdown
## 1 Background
## 2 Detail
## 3 Core Member
## 4 Doc Structure
## 5 How to Contribute
## 6 How to Subscribe
## 7 Thanks
```
@zmzhouXJTU

**Comment by zmzhouXJTU** [comment]
OK，I will finish it as quickly as possible
