### ISSUE TITLE
Collect references on the implementation of OS's threads.

### ISSUE THREAD

**Issue by wangqing1218** [ACLoong/Problem-sets#7]
Seeing that many followers know little about the content of  OS's thread & process,we should do something for it.
It's:
that collect references on the implementation of OS's thread.
All the book,paper, blog,course video and project will do.
You should list the detail of the chapter or file.
Also,the markdown file is greater than other format file.
@MrKingHH @jsondrm

**Comment by jsondrm** [comment]
that's fine.

**Comment by wangqing1218** [comment]
This issue can be closed.
