### ISSUE TITLE
Add An Introduction Page for Core Members.

### ISSUE THREAD

**Issue by wangqing1218** [ACLoong/Problem-sets#8]
It's necessary for us to introduce core members because of showing followers our organization structure.

Details:
In last week, the core members all introduce themselves, so tidy up infos about it.
Also, it must be a **.md** postfix's file in the master dir.
It's a nice opportunity for you to learn more skills for the open source git-flow.

**Comment by MrKingHH** [comment]
okay,i will finish this work as soon as possible

**Comment by zmzhouXJTU** [comment]
this issue can be closed
